### ISSUE TITLE
Events not delivered when connection is dropped

### ISSUE THREAD

**Issue by jcerjak** [fluent/fluent-logger-python#77] opened 2017-02-16 11:36 UTC
# Problem

We have a Fluentd instance running behind an Amazon Load Balancer. Load balancer has a [timeout setting](https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/config-idle-timeout.html) (defaults to 60s, for purposes of testing I have set it to 5s). As per docs: "If no data has been sent or received by the time that the idle timeout period elapses, the load balancer closes the connection."

When sending data, the FluentSender tries to reuse the connection if possible, and reconnect in case of a `socket.error`. If we keep sending events one after another (time between sends is < timeout) everything works fine. But if we consider the following example:

* Send event no. 1
* Wait for timeout (e.g. 10s)
* Send event no. 2

Since the connection has been closed by the load balancer, I would expect to receive a socket error when sending event no.2. But the FluentSender (or specifically, the `socket` object) does not seem to register that the connection was dropped. There is no error when sending event no. 2 (`emit` will return `True`), but the event never reaches the destination.

## Debugging info

This was tested on Python 2.7.6 and Python 3.4.3.

I have prepared some examples to demonstrate the issue. For simplicity, we are using the `socket` directly, without using the FluentSender.

### Example 1

In this example we send 1 event, then wait for timeout, and send a few more events. There is no socket error, even though the connection was dropped.

Code:

```python
import socket
import time

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.settimeout(3.0)
sock.connect(('myhost, 24224))

# send event no. 1
print('Sending event 1')
sock.sendall('event 1')

# wait for timeout
print('Waiting for timeout...')
time.sleep(10)

# send more events
for i in range(2, 10):
    print('Sending event {}'.format(i))
    sock.sendall('event {}'.format(i))
```

Output:

```
Sending event 1
Waiting for timeout...
Sending event 2
Sending event 3
Sending event 4
Sending event 5
Sending event 6
Sending event 7
Sending event 8
Sending event 9
Sending event 10
```

### Example 2

This is a similar example as Example 1, but with a short delay between additional events. In this case we do get a socket error, but only when trying to send the 4th event after the timeout.

Code:

```python
# ... snip

# send more events
for i in range(2, 10):
    print('Sending event {}'.format(i))
    sock.sendall('event {}'.format(i))

    # add a short delay before sending the next event
    time.sleep(0.1)
```

Output:

```
Sending event 1
Waiting for timeout...
Sending event 2
Sending event 3
Sending event 4
Sending event 5
Traceback (most recent call last):
  File "socktst.py", line 18, in <module>
    sock.sendall('event {}'.format(i))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 32] Broken pipe
```

# Solution?

One way of solving this would be to add an option to always reconnect (False by default), instead of reusing the connection. The problem might also be caused with the way the load balancer drops connections, but not sure how to check this. So any help on this is appreciated.

**Comment by nqbao** [comment] 2017-10-19 22:06
Is there any progress on this? I'm also suffering the same problem.

**Comment by repeatedly** [comment] 2017-10-19 23:41
Sorry, I missed this issue...

@nqbao Do you hit this problem with LB?

**Comment by repeatedly** [comment] 2017-10-19 23:46
I'm not familiar with python socket internal, so I don't know the best way to resolve it.
But if create socket at each write resolves the problem, adding option is no problem for me.

**Comment by nqbao** [comment] 2017-10-19 23:47
I am having a similar problem, not with LB.  

So basically, events are lost if the connection is lost.
You can try to reproduce this issue by:

1. Create a python script that generates events every 1s
2. Restart the fluentd server.
3. Some events will be lost

I can provide more details script if you need to.

**Comment by repeatedly** [comment] 2017-10-23 20:26
> I can provide more details script if you need to.

Could you show me your case?
I tried simple setup and it worked.

- fluent.conf with fluentd v0.14.22.rc1

```
<source>
  @type forward
</source>

<match test.**>
  @type stdout
</match>
```

- python script

```
from fluent import sender
import time

logger = sender.FluentSender('test')
i = 0
while True:
    msg = {'message':'hello','num':i}
    i += 1
    if not logger.emit('foo', msg):
        print(logger.last_error)
    time.sleep(1)
```

- log

```
[snip]
2017-10-24 04:35:19 +0900 [info]: #0 fluentd worker is now running worker=0
2017-10-24 04:35:24.000000000 +0900 test.foo: {"message":"hello","num":0}
2017-10-24 04:35:25.000000000 +0900 test.foo: {"message":"hello","num":1}
2017-10-24 04:35:26.000000000 +0900 test.foo: {"message":"hello","num":2}
2017-10-24 04:35:27.000000000 +0900 test.foo: {"message":"hello","num":3}
2017-10-24 04:35:28.000000000 +0900 test.foo: {"message":"hello","num":4}
2017-10-24 04:35:29.000000000 +0900 test.foo: {"message":"hello","num":5}
2017-10-24 04:35:30.000000000 +0900 test.foo: {"message":"hello","num":6}
^C2017-10-24 04:35:30 +0900 [info]: Received graceful stop
2017-10-24 04:35:31.000000000 +0900 test.foo: {"message":"hello","num":7}
[snip]
2017-10-24 04:35:32 +0900 [info]: Worker 0 finished with status 0
[snip]
2017-10-24 04:35:33 +0900 [info]: #0 fluentd worker is now running worker=0
2017-10-24 04:35:32.000000000 +0900 test.foo: {"message":"hello","num":8}
2017-10-24 04:35:33.000000000 +0900 test.foo: {"message":"hello","num":9}
2017-10-24 04:35:34.000000000 +0900 test.foo: {"message":"hello","num":10}
2017-10-24 04:35:35.000000000 +0900 test.foo: {"message":"hello","num":11}
2017-10-24 04:35:36.000000000 +0900 test.foo: {"message":"hello","num":12}
2017-10-24 04:35:37.000000000 +0900 test.foo: {"message":"hello","num":13}
2017-10-24 04:35:38.000000000 +0900 test.foo: {"message":"hello","num":14}
^C2017-10-24 04:35:39 +0900 [info]: Received graceful stop
2017-10-24 04:35:39.000000000 +0900 test.foo: {"message":"hello","num":15}
2017-10-24 04:35:40 +0900 [info]: #0 fluentd worker is now stopping worker=0
[snip]
2017-10-24 04:35:42 +0900 [info]: #0 fluentd worker is now running worker=0
2017-10-24 04:35:40.000000000 +0900 test.foo: {"message":"hello","num":16}
2017-10-24 04:35:41.000000000 +0900 test.foo: {"message":"hello","num":17}
2017-10-24 04:35:42.000000000 +0900 test.foo: {"message":"hello","num":18}
2017-10-24 04:35:43.000000000 +0900 test.foo: {"message":"hello","num":19}
2017-10-24 04:35:44.000000000 +0900 test.foo: {"message":"hello","num":20}
2017-10-24 04:35:45.000000000 +0900 test.foo: {"message":"hello","num":21}
^C2017-10-24 04:35:45 +0900 [info]: Received graceful stop
2017-10-24 04:35:46.000000000 +0900 test.foo: {"message":"hello","num":22}
2017-10-24 04:35:46 +0900 [info]: #0 fluentd worker is now stopping worker=0
[snip]
```

**Comment by arcivanov** [comment] 2017-12-04 10:39
The reason for this is a nature of TCP protocol and sub-optimal socket implementation in the logger. Unless the remote sends an application-level ["ack"](https://github.com/fluent/fluentd/wiki/Forward-Protocol-Specification-v0#response) that you thereafter receive, you cannot know if a message has been delivered. This is an absolute limitation of the TCP/IP (hence the TIMED_WAIT state on closing, since even closing a connection in TCP is unreliable). This is the reason why message queues are actually requiring acks for reliable delivery. In our case no chunking is used therefore no application level "ack" can be had, therefore there is always a possibility of losing data.

The second part of the problem is that `sendall` really is incapable of reporting if data was at all sent. `send` can do better but is not guaranteed to report the gone-receiver issue either - `send` writes into a network buffer which virtually always succeeds. The reliability of a send can be improved by disabling Nagle's protocol, at the cost of constantly flushing network buffer on every `send`. This, however, doesn't eliminate the uncertainty if the fluentd server actually received the data.

There can be multiple solutions to this:
1) sendall -> send
2) Turn off Nagle's 
3) Use buffer chunking and read the acks maintaining an application window of messages sent and retry if no acks are received.

**Closed** 2017-12-06 00:49 UTC

**Comment by nqbao** [comment] 2017-12-06 05:39
Great!
